version: "3.9"
services:
  server:
    build: .
    ports:
      - 8081:${SERVER_PORT}
    volumes:
      - ./files:/files
    environment:
      - SERVER_PORT=$SERVER_PORT
      - DATABASE_CONNECTION_STRING=$DATABASE_CONNECTION_STRING
      - POSTGRES_NAME=$POSTGRES_NAME
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - JWT_SECRET=$JWT_SECRET
      - JWT_AUDIENCE=$JWT_AUDIENCE
      - JWT_ISSUER=$JWT_ISSUER
      - JWT_ACCESS_LIFETIME=$JWT_ACCESS_LIFETIME
      - JWT_REFRESH_LIFETIME=$JWT_REFRESH_LIFETIME
      - ONESIGNAL_API_KEY=$ONESIGNAL_API_KEY
      - ONESIGNAL_APP_ID=$ONESIGNAL_APP_ID
      - KINOPOISK_API_TOKEN=$KINOPOISK_API_TOKEN
    depends_on:
      - db
    networks:
      - db_network
    restart: always

  db:
    image: ${POSTGRES_IMAGE}
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_DB: "f2g"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - ./db-data:/var/lib/postgresql/data
      - ./sql/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - db_network
    restart: always

networks:
  db_network:
    driver: bridge